version: 1
disable_existing_loggers: false


formatters:
  # 标准文本格式
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  # 详细文本格式（含进程/线程ID）
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(process)d - %(thread)d - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S.%f'
  # JSON格式（核心：指向正确的自定义格式化器）
  json:
    class: logger.CustomJsonFormatter  # 若在子目录则改为：app.utils.logger.CustomJsonFormatter
    format: '%(timestamp)s %(name)s %(level)s %(trace_id)s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S.%f'

# 日志处理器
handlers:
  # 控制台输出
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  # 普通应用日志文件
  app_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: ${LOG_FILE_PATH:-./logs/app.log}
    maxBytes: ${LOG_MAX_BYTES:-10485760}
    backupCount: ${LOG_BACKUP_COUNT:-5}
    encoding: utf8

  # 错误日志文件
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: ./logs/error.log
    maxBytes: 10485760
    backupCount: 5
    encoding: utf8

  # JSON格式API日志文件（无拼写错误）
  api_json_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: ./logs/api.json
    maxBytes: 10485760
    backupCount: 5
    encoding: utf8

# 日志记录器配置
loggers:
  # 根日志
  root:
    level: WARNING
    handlers: [ console, app_file, error_file ]
    propagate: no

  # 应用核心日志
  app:
    level: INFO
    handlers: [ console, app_file ]
    propagate: no

  # API请求/响应日志（关联JSON处理器）
  api.requests:
    level: INFO
    handlers: [ console, app_file, api_json_file ]
    propagate: no
  api.responses:
    level: INFO
    handlers: [ console, app_file, api_json_file ]
    propagate: no
  app.exceptions:
    level: ERROR
    handlers: [ console, error_file, api_json_file ]
    propagate: no

  # 第三方库日志管控
  uvicorn:
    level: WARNING
    handlers: [ console, app_file ]
    propagate: no
  uvicorn.access:
    level: WARNING
    handlers: [ console, app_file ]
    propagate: no
  sqlalchemy:
    level: WARNING
    handlers: [ console ]
    propagate: no
  fastapi:
    level: INFO
    handlers: [ console, app_file ]
    propagate: no
